[tool.poetry]
name = "BookMarketTG"
version = "0.1.0"
description = ""
authors = ["Adel <Aldavletshina777654@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.10"
python-telegram-bot = "^21.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
